### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by FrankRizz0** [arcolinux/arcolinux-polybar#1]
Does this file need to be updated?  I'm getting the error 'Error: Unable to print the data'

The only thing I've changed regarding the script is the API, CITY and colors

**Comment by arcolinuxz** [comment]
I have seen your question on youtube.
Let us continue here.
What element are you trying to use?
What module?

**Comment by FrankRizz0** [comment]
Weather module.

**Comment by arcolinuxz** [comment]
fixed - needed new api key code for website
