### ISSUE TITLE
launch.sh case statements missing

### ISSUE THREAD

**Issue by lucserre** [arcolinux/arcolinux-polybar#6]
New i3 installation (from ArcolinuxB) on a vm.
Switching i3's config to config-polybar, which starts launch.sh
In launsh.sh, my $DESKTOP_SESSION is "i3-with-shmlog" with is missing from the case statements, so it doesn't launch polybar.
Fix is appending an or statement:  " ... | i3-with-shmlog)" 
thanks

**Comment by arcolinuxz** [comment]
we are going to use that one
you will run into issues if you do
avoid that one

**Comment by lucserre** [comment]
Ok, well, it's not like I  made a choice to use "-with-shmlog", that's just what came got installed by default.

**Comment by arcolinuxz** [comment]
i know it is rubbish
do not know why it is there
